version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  auth:
    image: auth:latest
    restart: on-failure
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      DB_HOST: mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

  cadastro:
    image: cadastro:latest
    restart: on-failure
    build:
      context: ./cadastro
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge